version: "3.5"

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./app:/fastapi-app/app
    environment:
      - DATABASE_URL= 'postgresql://myuser:mypassword@localhost:5432/postgres'
    ports:
      - "8000:80"
    expose:
      - 8000

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    restart: always

volumes:
  postgres_data:
