version: "3.5"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/fastapi-app

  postgres:
    container_name: fastapi_postgres_container
    image: postgres:alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    container_name: fastapi_pgadmin_container
    environment:
      - PGADMIN

volumes:
  data:
